delete from users;
delete from ad_broadcasts;
delete from song_broadcasts;
delete from ads;
delete from songs;
delete from broadcasts;

insert into users (id, username, password, email, role) values(6001, 'producer', 'producer', 'producer@email.com', 'PRODUCER');
insert into users (id, username, password, email, role) values(6002, 'user', 'user', 'user@email.com', 'USER');

insert into ads (id, duration, rep_per_zone, starting_date, ending_date, timezone) values (1001, 9, 0, PARSEDATETIME('01-01-2022','dd-MM-yyyy'), PARSEDATETIME('01-03-2022','dd-MM-yyyy'), 'LateNight');
insert into ads (id, duration, rep_per_zone, starting_date, ending_date, timezone) values (1002, 30, 0, PARSEDATETIME('01-01-2022','dd-MM-yyyy'), PARSEDATETIME('01-04-2022','dd-MM-yyyy'), 'LateNight');

insert into songs (id, title, artist, release_year, duration, genre) values(7001, 'Ride', 'Twenty One Pilots', 2015, 25, 'hip hop');
insert into songs (id, title, artist, release_year, duration, genre) values(7002, 'Stressed Out', 'Twenty One Pilots', 2015, 5, 'hip hop');

insert into broadcasts (id, duration, starting_date, starting_time, type) values(3001, 200, PARSEDATETIME('01-02-2022','dd-MM-yyyy'), '00:00', 'PLAYLIST');
insert into broadcasts (id, duration, starting_date, starting_time, type) values(3002, 200, PARSEDATETIME('01-02-2023','dd-MM-yyyy'), '08:00', 'PLAYLIST');

insert into ad_broadcasts (id, broadcast_date, broadcast_time, ad_id, broadcast_id) values (4001, PARSEDATETIME('01-02-2022','dd-MM-yyyy'), '00:40', 1001, 3001);
insert into ad_broadcasts (id, broadcast_date, broadcast_time, ad_id, broadcast_id) values (4002, PARSEDATETIME('01-02-2022','dd-MM-yyyy'), '01:50', 1002, 3001);

insert into song_broadcasts (id, broadcast_date, broadcast_time, song_id, broadcast_id) values (5001, PARSEDATETIME('01-02-2022','dd-MM-yyyy'), '00:00', 7001, 3001);
insert into song_broadcasts (id, broadcast_date, broadcast_time, song_id, broadcast_id) values (5002, PARSEDATETIME('01-02-2022','dd-MM-yyyy'), '01:10', 7002, 3001);

INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7010,'Hey, Soul Sister','Train','neo mellow',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7011,'Love The Way You Lie','Eminem','hip hop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7012,'TiK ToK','Kesha','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7013,'Bad Romance','Lady Gaga','pop',2010,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7014,'Just the Way You Are','Bruno Mars','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7015,'Baby','Justin Bieber','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7016,'Dynamite','Taio Cruz','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7017,'Secrets','OneRepublic','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7018,'Empire State of Mind (Part II) Broken Down','Alicia Keys','hip pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7019,'Only Girl (In The World)','Rihanna','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7020,'Club Can''t Handle Me (feat. David Guetta)','Flo Rida','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7021,'Marry You','Bruno Mars','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7022,'Cooler Than Me - Single Mix','Mike Posner','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7023,'Telephone','Lady Gaga','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7024,'Like A G6','Far East Movement','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7025,'OMG (feat. will.i.am)','Usher','hip hop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7026,'Eenie Meenie','Sean Kingston','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7027,'The Time (Dirty Bit)','The Black Eyed Peas','pop',2010,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7028,'Alejandro','Lady Gaga','pop',2010,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7029,'Your Love Is My Drug','Kesha','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7030,'Meet Me Halfway','The Black Eyed Peas','pop',2010,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7031,'Whataya Want from Me','Adam Lambert','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7032,'Take It Off','Kesha','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7033,'Misery','Maroon 5','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7034,'All The Right Moves','OneRepublic','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7035,'Animal','Neon Trees','indie pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7036,'Naturally','Selena Gomez & The Scene','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7037,'I Like It','Enrique Iglesias','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7038,'Teenage Dream','Katy Perry','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7039,'California Gurls','Katy Perry','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7040,'3','Britney Spears','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7041,'My First Kiss - feat. Ke$ha','3OH!3','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7042,'Blah Blah Blah (feat. 3OH!3)','Kesha','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7043,'Imma Be','The Black Eyed Peas','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7044,'Try Sleeping with a Broken Heart','Alicia Keys','hip pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7045,'Sexy Bitch (feat. Akon)','David Guetta','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7046,'Bound To You - Burlesque Original Motion Picture Soundtrack','Christina Aguilera','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7047,'If I Had You','Adam Lambert','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7048,'Rock That Body','The Black Eyed Peas','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7049,'Dog Days Are Over','Florence + The Machine','art pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7050,'Something''s Got A Hold On Me - Burlesque Original Motion Picture Soundtrack','Christina Aguilera','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7051,'Doesn''t Mean Anything','Alicia Keys','hip pop',2010,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7052,'Hard','Rihanna','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7053,'Loca','Shakira','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7054,'You Lost Me','Christina Aguilera','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7055,'Not Myself Tonight','Christina Aguilera','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7056,'Written in the Stars (feat. Eric Turner)','Tinie Tempah','pop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7057,'DJ Got Us Fallin'' In Love (feat. Pitbull)','Usher','hip hop',2010,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7058,'Castle Walls (feat. Christina Aguilera)','T.I.','hip hop',2010,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7059,'Break Your Heart','Taio Cruz','pop',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7060,'Hello','Martin Solveig','big room',2010,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7061,'A Thousand release_years','Christina Perri','pop',2011,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7062,'Someone Like You','Adele','soul',2011,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7063,'Give Me Everything','Pitbull','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7064,'Just the Way You Are','Bruno Mars','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7065,'Rolling in the Deep','Adele','soul',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7066,'Run the World (Girls)','Beyonc','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7067,'Moves Like Jagger - Studio Recording From The Voice Performance','Maroon 5','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7068,'Love On Top','Beyonc','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7069,'Grenade','Bruno Mars','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7070,'Tonight Tonight','Hot Chelle Rae','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7071,'What the Hell','Avril Lavigne','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7072,'Born This Way','Lady Gaga','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7073,'Monster','Kanye West','rap',2011,6);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7074,'Marry You','Bruno Mars','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7075,'Best Thing I Never Had','Beyonc','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7076,'Party Rock Anthem','LMFAO','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7077,'We R Who We R','Kesha','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7078,'Price Tag','Jessie J','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7079,'Good Life','OneRepublic','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7080,'Just Cant Get Enough','The Black Eyed Peas','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7081,'On The Floor','Jennifer Lopez','pop',2011,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7082,'What''s My Name?','Rihanna','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7083,'Yeah 3x','Chris Brown','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7084,'Without You (feat. Usher)','David Guetta','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7085,'Sexy And I Know It','LMFAO','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7086,'The Edge Of Glory','Lady Gaga','pop',2011,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7087,'E.T.','Katy Perry','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7088,'Till the World Ends','Britney Spears','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7089,'I Wanna Go','Britney Spears','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7090,'Blow','Kesha','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7091,'You And I','Lady Gaga','pop',2011,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7092,'Judas','Lady Gaga','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7093,'Tonight (I''m Fuckin'' You)','Enrique Iglesias','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7094,'Please Don''t Go','Mike Posner','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7095,'We Found Love','Rihanna','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7096,'Marry The Night','Lady Gaga','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7097,'1+1','Beyonc','pop',2011,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7098,'Hold It Against Me','Britney Spears','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7099,'I''m Into You','Jennifer Lopez','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7100,'Papi','Jennifer Lopez','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7101,'Cheers (Drink To That)','Rihanna','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7102,'S&M Remix','Rihanna','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7103,'Written in the Stars (feat. Eric Turner)','Tinie Tempah','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7104,'Jar of Hearts','Christina Perri','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7105,'Castle Walls (feat. Christina Aguilera)','T.I.','hip hop',2011,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7106,'Turning Page','Sleeping At Last','acoustic pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7107,'Super Bass','Nicki Minaj','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7108,'Raise Your Glass','P!nk','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7109,'Invading My Mind','Jennifer Lopez','pop',2011,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7110,'Moment 4 Life - Album Version (Edited)','Nicki Minaj','pop',2011,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7111,'Last Friday Night (T.G.I.F.)','Katy Perry','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7112,'Firework','Katy Perry','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7113,'Muny - Album Version (Edited)','Nicki Minaj','pop',2011,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7114,'Titanium (feat. Sia)','David Guetta','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7115,'Locked Out of Heaven','Bruno Mars','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7116,'Paradise','Coldplay','permanent wave',2012,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7117,'Payphone','Maroon 5','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7118,'What Makes You Beautiful','One Direction','boy band',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7119,'I Knew You Were Trouble.','Taylor Swift','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7120,'Call Me Maybe','Carly Rae Jepsen','pop',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7121,'Love You Like A Love songs','Selena Gomez & The Scene','pop',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7122,'Set Fire to the Rain','Adele','soul',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7123,'We Are Never Ever Getting Back Together','Taylor Swift','pop',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7124,'Stronger (What Doesn''t Kill You)','Kelly Clarkson','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7125,'Try','P!nk','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7126,'Starships','Nicki Minaj','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7127,'One More Night','Maroon 5','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7128,'Good Time','Owl City','pop',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7129,'Glad You Came','The Wanted','boy band',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7130,'Beauty And A Beat','Justin Bieber','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7131,'International Love','Pitbull','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7132,'Some Nights','fun.','pop',2012,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7133,'Boyfriend','Justin Bieber','pop',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7134,'Part Of Me','Katy Perry','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7135,'Domino','Jessie J','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7136,'Where Have You Been','Rihanna','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7137,'Wide Awake','Katy Perry','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7138,'The One That Got Away','Katy Perry','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7139,'Dance Again','Jennifer Lopez','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7140,'Turn Up the Music','Chris Brown','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7141,'Lights - Single Version','Ellie Goulding','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7142,'We Are Young (feat. Janelle Mone)','fun.','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7143,'Diamonds','Rihanna','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7144,'Don''t Stop the Party (feat. TJR)','Pitbull','pop',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7145,'You Da One','Rihanna','pop',2012,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7146,'Stereo Hearts (feat. Adam Levine)','Gym Class Heroes','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7147,'It Will Rain','Bruno Mars','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7148,'Blow Me (One Last Kiss)','P!nk','pop',2012,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7149,'Underneath the Tree','Kelly Clarkson','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7150,'Wake Me Up','Avicii','big room',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7151,'Story of My Life','One Direction','boy band',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7152,'Just Give Me a Reason (feat. Nate Ruess)','P!nk','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7153,'Hall of Fame','The Script','celtic rock',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7154,'Roar','Katy Perry','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7155,'We Can''t Stop','Miley Cyrus','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7156,'Don''t You Worry Child - Radio Edit','Swedish House Mafia','big room',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7157,'Get Lucky (feat. Pharrell Williams & Nile Rodgers) - Radio Edit','Daft Punk','electro',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7158,'Wrecking Ball','Miley Cyrus','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7159,'Impossible','James Arthur','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7160,'Blurred Lines','Robin Thicke','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7161,'Heart Attack','Demi Lovato','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7162,'We Are Never Ever Getting Back Together','Taylor Swift','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7163,'Die Young','Kesha','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7164,'Clarity','Zedd','complextro',2013,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7165,'Summertime Sadness (Lana Del Rey Vs. Cedric Gervais) - Cedric Gervais Remix','Lana Del Rey','art pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7166,'Under Control','Calvin Harris','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7167,'Everybody Talks','Neon Trees','indie pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7168,'Hold On, We''re Going Home','Drake','canadian hip hop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7169,'Best songs Ever','One Direction','boy band',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7170,'Kiss You','One Direction','boy band',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7171,'Sweet Nothing (feat. Florence Welch)','Calvin Harris','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7172,'Lose Yourself to Dance','Daft Punk','electro',2013,6);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7173,'Work Bitch','Britney Spears','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7174,'Brave','Sara Bareilles','acoustic pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7175,'Can''t Hold Us (feat. Ray Dalton)','Macklemore & Ryan Lewis','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7176,'Feel This Moment (feat. Christina Aguilera)','Pitbull','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7177,'Beneath Your Beautiful','Labrinth','pop',2013,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7178,'Let Me Love You (Until You Learn To Love Yourself)','Ne-Yo','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7179,'Thrift Shop (feat. Wanz)','Macklemore & Ryan Lewis','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7180,'If I Lose Myself - Alesso vs OneRepublic','OneRepublic','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7181,'I Love It (feat. Charli XCX)','Icona Pop','candy pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7182,'Play Hard (feat. Ne-Yo & Akon) - New Edit','David Guetta','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7183,'Daylight','Maroon 5','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7184,'Love Somebody','Maroon 5','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7185,'A Little Party Never Killed Nobody (All We Got)','Fergie','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7186,'Move','Little Mix','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7187,'Walks Like Rihanna','The Wanted','boy band',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7188,'Rock N Roll','Avril Lavigne','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7189,'Heartbreaker','Justin Bieber','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7190,'Mirrors - Radio Edit','Justin Timberlake','pop',2013,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7191,'Next To Me','Emeli Sand','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7192,'Made In The USA','Demi Lovato','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7193,'Clown','Emeli Sand','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7194,'Girl On Fire (feat. Nicki Minaj) - Inferno Version','Alicia Keys','hip pop',2013,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7195,'TKO','Justin Timberlake','pop',2013,7);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7196,'Come & Get It','Selena Gomez','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7197,'Live It Up','Jennifer Lopez','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7198,'We Own The Night','The Wanted','boy band',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7199,'Atlas - From The Hunger Games: Catching Fire Soundtrack','Coldplay','permanent wave',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7200,'What About Love','Austin Mahone','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7201,'Take Back the Night','Justin Timberlake','pop',2013,6);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7202,'Applause','Lady Gaga','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7203,'Anything Could Happen','Ellie Goulding','pop',2013,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7204,'Finally Found You','Enrique Iglesias','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7205,'People Like Us','Kelly Clarkson','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7206,'Overdose','Ciara','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7207,'Right Now - Dyro Radio Edit','Rihanna','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7208,'Give It 2 U','Robin Thicke','pop',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7209,'Foolish Games','Jewel','alaska indie',2013,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7210,'Outta Nowhere (feat. Danny Mercer)','Pitbull','pop',2013,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7211,'Freak','Kelly Rowland','hip hop',2013,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7212,'All of Me','John Legend','neo mellow',2014,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7213,'Stay With Me','Sam Smith','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7214,'Summer','Calvin Harris','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7215,'Happy - From "Despicable Me 2"','Pharrell Williams','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7216,'Rude','MAGIC!','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7217,'Shake It Off','Taylor Swift','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7218,'Dark Horse','Katy Perry','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7219,'Hey Brother','Avicii','big room',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7220,'Maps','Maroon 5','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7221,'Treasure','Bruno Mars','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7222,'Let Her Go','Passenger','folk-pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7223,'Problem','Ariana Grande','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7224,'Pompeii','Bastille','metropopolis',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7225,'Team','Lorde','art pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7226,'Love Me Again','John Newman','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7227,'Latch','Disclosure','house',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7228,'Adore You','Miley Cyrus','pop',2014,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7229,'Love Never Felt So Good','Michael Jackson','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7230,'Burn','Ellie Goulding','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7231,'She Looks So Perfect','5 Seconds of Summer','boy band',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7232,'Fancy','Iggy Azalea','australian hip hop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7233,'Talk Dirty (feat. 2 Chainz)','Jason Derulo','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7234,'Gorilla','Bruno Mars','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7235,'human','Christina Perri','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7236,'Young Girls','Bruno Mars','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7237,'Wiggle (feat. Snoop Dogg)','Jason Derulo','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7238,'Love Runs Out','OneRepublic','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7239,'This Is How We Do','Katy Perry','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7240,'Mmm Yeah (feat. Pitbull)','Austin Mahone','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7241,'Partition','Beyonc','pop',2014,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7242,'Birthday','Katy Perry','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7243,'Let It Go - From Frozen / Single Version','Demi Lovato','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7244,'Wings','Birdy','neo mellow',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7245,'Can''t Remember to Forget You (feat. Rihanna)','Shakira','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7246,'Shot Me Down (feat. Skylar Grey) - Radio Edit','David Guetta','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7247,'Say Something','A Great Big World','neo mellow',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7248,'A Sky Full of Stars','Coldplay','permanent wave',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7249,'Come Get It Bae','Pharrell Williams','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7250,'Chandelier','Sia','dance',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7251,'XO','Beyonc','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7252,'We Are One (Ole Ola) [The Official 2014 FIFA World Cup songs]','Pitbull','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7253,'Not About Angels','Birdy','neo mellow',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7254,'Drunk in Love','Beyonc','pop',2014,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7255,'Anaconda','Nicki Minaj','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7256,'Boom Clap - From the Motion Picture Das Schicksal ist ein mieser Verrter','Charli XCX','candy pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7257,'La La La (Brasil 2014) (feat. Carlinhos Brown)','Shakira','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7258,'Tee Shirt - Soundtrack Version','Birdy','neo mellow',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7259,'Words as Weapons','Birdy','neo mellow',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7260,'You''re Mine (Eternal)','Mariah Carey','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7261,'Sheezus','Lily Allen','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7262,'Cannonball','Lea Michele','hollywood',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7263,'It''s On Again - Main Soundtrack','Alicia Keys','hip pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7264,'I Luh Ya Papi','Jennifer Lopez','pop',2014,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7265,'Not a Bad Thing','Justin Timberlake','pop',2014,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7266,'Thinking out Loud','Ed Sheeran','pop',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7267,'I''m Not The Only One','Sam Smith','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7268,'The Hills','The Weeknd','r&b',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7269,'Love Yourself','Justin Bieber','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7270,'Uptown Funk','Mark Ronson','pop',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7271,'Take Me To Church','Hozier','irish singer-songswriter',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7272,'Sugar','Maroon 5','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7273,'Sorry','Justin Bieber','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7274,'FourFiveSeconds','Rihanna','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7275,'Love Me Like You Do - From "Fifty Shades Of Grey"','Ellie Goulding','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7276,'Earned It (Fifty Shades Of Grey) - From The "Fifty Shades Of Grey" Soundtrack','The Weeknd','r&b',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7277,'What Do You Mean?','Justin Bieber','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7278,'Stitches','Shawn Mendes','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7279,'Want to Want Me','Jason Derulo','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7280,'My House','Flo Rida','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7281,'Waves - Robin Schulz Radio Edit','Mr. Probz','house',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7282,'Night Changes','One Direction','boy band',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7283,'How Deep Is Your Love','Calvin Harris','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7284,'Never Forget You','Zara Larsson','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7285,'Love Me Harder','Ariana Grande','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7286,'Animals','Maroon 5','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7287,'Blame','Calvin Harris','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7288,'Worth It','Fifth Harmony','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7289,'Break Free','Ariana Grande','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7290,'Don''t','Ed Sheeran','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7291,'Elastic Heart','Sia','dance',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7292,'Rather Be (feat. Jess Glynne)','Clean Bandit','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7293,'Hello','Adele','soul',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7294,'Dear Future Husband','Meghan Trainor','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7295,'43776','Beyonc','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7296,'The Heart Wants What It Wants','Selena Gomez','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7297,'Hey Mama (feat. Nicki Minaj, Bebe Rexha & Afrojack)','David Guetta','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7298,'Genie In a Bottle','Christina Aguilera','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7299,'Company','Justin Bieber','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7300,'Sing','Ed Sheeran','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7301,'Jealous - Remix','Nick Jonas','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7302,'Really Don''t Care','Demi Lovato','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7303,'Downtown (feat. Melle Mel, Grandmaster Caz, Kool Moe Dee & Eric Nally)','Macklemore & Ryan Lewis','pop',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7304,'Only Love Can Hurt Like This','Paloma Faith','soul',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7305,'Heartbeat songs','Kelly Clarkson','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7306,'Up','Olly Murs','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7307,'Trumpets','Jason Derulo','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7308,'Runnin'' (Lose It All)','Naughty Boy','house',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7309,'Same Old Love','Selena Gomez','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7310,'I Want You To Know','Zedd','complextro',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7311,'Lips Are Movin','Meghan Trainor','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7312,'I''ll Show You','Justin Bieber','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7313,'Here','Alessia Cara','r&b',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7314,'I Lived','OneRepublic','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7315,'Fireball (feat. John Ryan)','Pitbull','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7316,'Easy Love','Sigala','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7317,'The Feeling','Justin Bieber','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7318,'I Really Like You','Carly Rae Jepsen','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7319,'BO$$','Fifth Harmony','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7320,'Sugar','Maroon 5','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7321,'Focus','Ariana Grande','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7322,'All About That Bass','Meghan Trainor','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7323,'On My Mind','Ellie Goulding','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7324,'Love Me Like You','Little Mix','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7325,'Broken Arrows','Avicii','big room',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7326,'Booty','Jennifer Lopez','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7327,'What Do You Mean? - Acoustic','Justin Bieber','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7328,'Mark My Words','Justin Bieber','pop',2015,2);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7329,'Lay It All on Me','Rudimental','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7330,'American Oxygen','Rihanna','pop',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7331,'Bang Bang','Jessie J','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7332,'Reality - Radio Edit','Lost Frequencies','belgian edm',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7333,'Alive','Sia','dance',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7334,'Sugar (feat. Francesco Yates)','Robin Schulz','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7335,'Been You','Justin Bieber','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7336,'Prayer in C - Robin Schulz Radio Edit','Lilly Wood and The Prick','french indie pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7337,'See You Again (feat. Charlie Puth)','Wiz Khalifa','hip hop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7338,'Heroes (we could be)','Alesso','big room',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7339,'Feel The Light - From The "Home" Soundtrack','Jennifer Lopez','pop',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7340,'Perfect','One Direction','boy band',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7341,'Ghosttown','Madonna','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7342,'Bang My Head (feat. Sia & Fetty Wap)','David Guetta','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7343,'Bloodstream','Ed Sheeran','pop',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7344,'Living For Love','Madonna','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7345,'Baby Don''t Lie','Gwen Stefani','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7346,'Don''t Be so Hard on Yourself','Jess Glynne','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7347,'Steal My Girl','One Direction','boy band',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7348,'Celebrate (From the Original Motion Picture "Penguins of Madagascar")','Pitbull','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7349,'We Are Here','Alicia Keys','hip pop',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7350,'St Jude','Florence + The Machine','art pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7351,'Yesterday (feat. Bebe Rexha)','David Guetta','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7352,'Time of Our Lives','Pitbull','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7353,'Sparks','Hilary Duff','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7354,'Mr. Put It Down','Ricky Martin','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7355,'Legendary Lovers','Katy Perry','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7356,'Spark The Fire','Gwen Stefani','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7357,'Run Run Run','Kelly Clarkson','pop',2015,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7358,'Let Me Be Your Lover','Enrique Iglesias','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7359,'Dangerous','Jennifer Hudson','pop',2015,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7360,'L.A.LOVE (la la)','Fergie','pop',2015,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7361,'The Hills','The Weeknd','r&b',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7362,'Love Yourself','Justin Bieber','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7363,'Cake By The Ocean','DNCE','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7364,'Don''t Let Me Down','The Chainsmokers','electro',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7365,'In the Name of Love','Martin Garrix','big room',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7366,'Into You','Ariana Grande','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7367,'This Is What You Came For','Calvin Harris','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7368,'Million Reasons','Lady Gaga','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7369,'Needed Me','Rihanna','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7370,'7 release_years','Lukas Graham','danish pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7371,'CAN''T STOP THE FEELING! (Original songs from DreamWorks Animation''s "TROLLS")','Justin Timberlake','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7372,'Work from Home (feat. Ty Dolla $ign)','Fifth Harmony','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7373,'Scars To Your Beautiful','Alessia Cara','r&b',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7374,'Like I''m Gonna Lose You (feat. John Legend)','Meghan Trainor','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7375,'Work','Rihanna','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7376,'Stitches','Shawn Mendes','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7377,'Me, Myself & I','G-Eazy','hip hop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7378,'I Took A Pill In Ibiza - Seeb Remix','Mike Posner','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7379,'Dangerous Woman','Ariana Grande','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7380,'Starving','Hailee Steinfeld','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7381,'Shout Out to My Ex','Little Mix','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7382,'Electric Love','BRNS','electro',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7383,'Confident','Demi Lovato','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7384,'Too Good','Drake','canadian hip hop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7385,'Roses','The Chainsmokers','electro',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7386,'Cold Water (feat. Justin Bieber & M)','Major Lazer','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7387,'Me Too','Meghan Trainor','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7388,'Light It Up (feat. Nyla & Fuse ODG) [Remix]','Major Lazer','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7389,'Ain''t Your Mama','Jennifer Lopez','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7390,'Close','Nick Jonas','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7391,'Toothbrush','DNCE','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7392,'All We Know','The Chainsmokers','electro',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7393,'Final songs','M','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7394,'Company','Justin Bieber','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7395,'Hands To Myself','Selena Gomez','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7396,'All I Ask','Adele','soul',2016,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7397,'Just Like Fire (From the Original Motion Picture "Alice Through The Looking Glass")','P!nk','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7398,'NO','Meghan Trainor','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7399,'Kill Em With Kindness','Selena Gomez','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7400,'Cool Girl','Tove Lo','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7401,'Runnin'' (Lose It All)','Naughty Boy','house',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7402,'Here','Alessia Cara','r&b',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7403,'Perfect Illusion','Lady Gaga','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7404,'PILLOWTALK','ZAYN','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7405,'Out Of The Woods','Taylor Swift','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7406,'Rise','Katy Perry','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7407,'Wherever I Go','OneRepublic','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7408,'Body Say','Demi Lovato','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7409,'Don''t Be A Fool','Shawn Mendes','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7410,'LIKE I WOULD','ZAYN','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7411,'Cheap Thrills','Sia','dance',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7412,'I Got You','Bebe Rexha','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7413,'Run Away With Me','Carly Rae Jepsen','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7414,'Cruel (feat. ZAYN)','Snakehips','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7415,'Send My Love (To Your New Lover)','Adele','soul',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7416,'WTF (Where They From)','Missy Elliott','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7417,'Desire','release_years & release_years','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7418,'When We Were Young','Adele','soul',2016,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7419,'I Know What You Did Last Summer','Shawn Mendes','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7420,'Wish That You Were Here - From Miss Peregrines Home for Peculiar Children Original Motion Picture','Florence + The Machine','art pop',2016,7);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7421,'Hurts','Emeli Sand','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7422,'Change','Christina Aguilera','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7423,'Make Me... (feat. G-Eazy)','Britney Spears','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7424,'Keeping Your Head Up','Birdy','neo mellow',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7425,'True Colors','Zedd','complextro',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7426,'Make Me Like You','Gwen Stefani','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7427,'Champagne Problems','Nick Jonas','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7428,'Blown','DNCE','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7429,'Start','John Legend','neo mellow',2016,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7430,'Pep Rally','Missy Elliott','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7431,'Higher','Carly Rae Jepsen','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7432,'Invitation','Britney Spears','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7433,'One Call Away (feat. Tyga) - Remix','Charlie Puth','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7434,'Beautiful Birds (feat. Birdy)','Passenger','folk-pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7435,'Little Lies','Hilary Duff','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7436,'Do You Wanna Come Over?','Britney Spears','pop',2016,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7437,'BURNITUP!','Janet Jackson','pop',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7438,'Picky - Remix','Joey Montana','latin',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7439,'Behind Your Back','Nelly Furtado','canadian latin',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7440,'Million release_years Ago','Adele','soul',2016,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7441,'Shape of You','Ed Sheeran','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7442,'Closer','The Chainsmokers','electro',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7443,'Starboy','The Weeknd','r&b',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7444,'Treat You Better','Shawn Mendes','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7445,'That''s What I Like','Bruno Mars','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7446,'Let Me Love You','DJ Snake','electronic trap',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7447,'I Feel It Coming','The Weeknd','r&b',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7448,'Mercy','Shawn Mendes','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7449,'Side To Side','Ariana Grande','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7450,'Stay','Zedd','complextro',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7451,'It Ain''t Me (with Selena Gomez)','Kygo','edm',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7452,'Malibu','Miley Cyrus','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7453,'Something Just Like This','The Chainsmokers','electro',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7454,'Rockabye (feat. Sean Paul & Anne-Marie)','Clean Bandit','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7455,'I Dont Wanna Live Forever (Fifty Shades Darker)','ZAYN','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7456,'My Way','Calvin Harris','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7457,'I''m the One (feat. Justin Bieber, Quavo, Chance the Rapper & Lil Wayne)','DJ Khaled','pop',2017,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7458,'Praying','Kesha','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7459,'Despacito - Remix','Luis Fonsi','latin',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7460,'The Greatest','Sia','dance',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7461,'There for You','Martin Garrix','big room',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7462,'Paris','The Chainsmokers','electro',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7463,'Crying in the Club','Camila Cabello','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7464,'Mama','Jonas Blue','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7465,'Slide (feat. Frank Ocean & Migos)','Calvin Harris','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7466,'Swish Swish','Katy Perry','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7467,'Chained To The Rhythm','Katy Perry','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7468,'Cold (feat. Future)','Maroon 5','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7469,'Love','Lana Del Rey','art pop',2017,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7470,'Reggaetn Lento (Remix)','CNCO','boy band',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7471,'All I Ask','Adele','soul',2017,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7472,'First Time','Kygo','edm',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7473,'The Cure','Lady Gaga','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7474,'How Far I''ll Go - From "Moana"','Alessia Cara','r&b',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7475,'Bodak Yellow','Cardi B','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7476,'Rich Love (with Seeb)','OneRepublic','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7477,'Tired','Alan Walker','house',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7478,'Came Here for Love','Sigala','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7479,'24K Magic','Bruno Mars','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7480,'Strip That Down (feat. Quavo)','Liam Payne','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7481,'Cut To The Feeling','Carly Rae Jepsen','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7482,'OK - Spotify Version','Robin Schulz','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7483,'Bon apptit','Katy Perry','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7484,'Summer Bummer (feat. A$AP Rocky & Playboi Carti)','Lana Del Rey','art pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7485,'Get Low (with Liam Payne)','Zedd','complextro',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7486,'Kissing Strangers','DNCE','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7487,'Slow Hands','Niall Horan','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7488,'Younger Now','Miley Cyrus','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7489,'Body Moves','DNCE','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7490,'Reality (feat. Janieck Devy) - Radio Edit','Lost Frequencies','belgian edm',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7491,'Angel','Fifth Harmony','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7492,'Touch (feat. Kid Ink)','Little Mix','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7493,'We Don''t Talk Anymore - DROELOE Remix','Charlie Puth','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7494,'Love Incredible (feat. Camila Cabello)','Cashmere Cat','downtempo',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7495,'No Vacancy (with Sebastin Yatra)','OneRepublic','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7496,'Rich Boy','Galantis','big room',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7497,'Lust for Life (with The Weeknd)','Lana Del Rey','art pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7498,'Greenlight (feat. Flo Rida & LunchMoney Lewis)','Pitbull','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7499,'Influence','Tove Lo','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7500,'Remember I Told You','Nick Jonas','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7501,'Messin'' Around','Pitbull','pop',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7502,'Water Under the Bridge','Adele','soul',2017,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7503,'Free Me','Sia','dance',2017,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7504,'Kissing Strangers - Remix','DNCE','pop',2017,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7505,'A L I E N S','Coldplay','permanent wave',2017,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7506,'One Kiss (with Dua Lipa)','Calvin Harris','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7507,'Havana (feat. Young Thug)','Camila Cabello','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7508,'I Like It','Cardi B','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7509,'New Rules','Dua Lipa','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7510,'There''s Nothing Holdin'' Me Back','Shawn Mendes','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7511,'no tears left to cry','Ariana Grande','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7512,'IDGAF','Dua Lipa','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7513,'In My Blood','Shawn Mendes','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7514,'Wolves','Selena Gomez','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7515,'Dusk Till Dawn - Radio Edit','ZAYN','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7516,'Attention','Charlie Puth','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7517,'Electricity (with Dua Lipa)','Silk City','edm',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7518,'Love On The Brain','Rihanna','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7519,'Let Me Go (with Alesso, Florida Georgia Line & watt)','Hailee Steinfeld','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7520,'Silence','Marshmello','brostep',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7521,'Sorry Not Sorry','Demi Lovato','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7522,'Shallow - Radio Edit','Lady Gaga','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7523,'These Days','Rudimental','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7524,'What Lovers Do (feat. SZA)','Maroon 5','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7525,'Finesse - Remix; feat. Cardi B','Bruno Mars','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7526,'Perfect Duet (Ed Sheeran & Beyonc)','Ed Sheeran','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7527,'Bad At Love','Halsey','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7528,'Him & I (with Halsey)','G-Eazy','hip hop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7529,'Friends (with BloodPop)','Justin Bieber','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7530,'Wild Thoughts (feat. Rihanna & Bryson Tiller)','DJ Khaled','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7531,'My My My!','Troye Sivan','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7532,'Capital Letters','Hailee Steinfeld','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7533,'Sick Boy','The Chainsmokers','electro',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7534,'Tequila','Dan + Shay','contemporary country',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7535,'Look What You Made Me Do','Taylor Swift','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7536,'Youth (feat. Khalid)','Shawn Mendes','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7537,'Bad Liar','Selena Gomez','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7538,'Anywhere','Rita Ora','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7539,'Say Something','Justin Timberlake','pop',2018,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7540,'Chun-Li','Nicki Minaj','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7541,'Sign of the Times','Harry Styles','pop',2018,6);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7542,'Familiar','Liam Payne','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7543,'Let Me','ZAYN','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7544,'Supernova','Ansel Elgort','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7545,'Nervous','Shawn Mendes','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7546,'First Time','Kygo','edm',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7547,'End Game','Taylor Swift','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7548,'Mi Gente (feat. Beyonc)','J Balvin','latin',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7549,'Lemon','N.E.R.D','hip hop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7550,'For You (With Rita Ora)','Liam Payne','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7551,'Want To','Dua Lipa','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7552,'What I Need (feat. Kehlani)','Hayley Kiyoko','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7553,'Wait','Maroon 5','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7554,'What About Us','P!nk','pop',2018,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7555,'Kissing Strangers','DNCE','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7556,'2U (feat. Justin Bieber)','David Guetta','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7557,'Walk On Water (feat. Beyonc)','Eminem','hip hop',2018,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7558,'This Town','Niall Horan','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7559,'Girls (feat. Cardi B, Bebe Rexha & Charli XCX)','Rita Ora','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7560,'MOVE TO MIAMI','Enrique Iglesias','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7561,'Miss You (with Major Lazer & Tory Lanez)','Cashmere Cat','downtempo',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7562,'Filthy','Justin Timberlake','pop',2018,5);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7563,'Never Be the Same - Radio Edit','Camila Cabello','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7564,'Ferrari','Bebe Rexha','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7565,'Supplies','Justin Timberlake','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7566,'Boom Boom','RedOne','moroccan pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7567,'...Ready For It? - BloodPop Remix','Taylor Swift','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7568,'Drip (feat. Migos)','Cardi B','pop',2018,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7569,'Tell Me You Love Me - NOTD Remix','Demi Lovato','pop',2018,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7570,'Memories','Maroon 5','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7571,'Lose You To Love Me','Selena Gomez','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7572,'Someone You Loved','Lewis Capaldi','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7573,'Seorita','Shawn Mendes','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7574,'How Do You Sleep?','Sam Smith','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7575,'South of the Border (feat. Camila Cabello & Cardi B)','Ed Sheeran','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7576,'Trampoline (with ZAYN)','SHAED','electro',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7577,'Happier','Marshmello','brostep',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7578,'Truth Hurts','Lizzo','escape room',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7579,'Good as Hell (feat. Ariana Grande) - Remix','Lizzo','escape room',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7580,'Higher Love','Kygo','edm',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7581,'Only Human','Jonas Brothers','boy band',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7582,'Beautiful People (feat. Khalid)','Ed Sheeran','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7583,'Sucker','Jonas Brothers','boy band',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7584,'Don''t Call Me Up','Mabel','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7585,'I Don''t Care (with Justin Bieber)','Ed Sheeran','pop',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7586,'Talk (feat. Disclosure)','Khalid','r&b',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7587,'Giant (with Rag''n''Bone Man)','Calvin Harris','pop',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7588,'Takeaway','The Chainsmokers','electro',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7589,'All Around The World (La La La)','R3HAB','big room',2019,2);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7590,'Girls Like You (feat. Cardi B)','Maroon 5','pop',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7591,'Call You Mine','The Chainsmokers','electro',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7592,'No Guidance (feat. Drake)','Chris Brown','pop',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7593,'Antisocial (with Travis Scott)','Ed Sheeran','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7594,'Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)','DJ Snake','electronic trap',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7595,'Con Calma - Remix','Daddy Yankee','latin',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7596,'Find U Again (feat. Camila Cabello)','Mark Ronson','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7597,'Cross Me (feat. Chance the Rapper & PnB Rock)','Ed Sheeran','pop',2019,3);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7598,'No Brainer (feat. Justin Bieber, Chance the Rapper & Quavo)','DJ Khaled','pop',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7599,'Nothing Breaks Like a Heart (feat. Miley Cyrus)','Mark Ronson','pop',2019,4);
INSERT INTO songs (id, title,artist,genre,release_year,duration) VALUES (7600,'Kills You Slowly','The Chainsmokers','electro',2019,4);

INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1010, 9, 4, PARSEDATETIME('17-02-2023', 'dd-MM-yyyy'), PARSEDATETIME('13-05-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1011, 9, 1, PARSEDATETIME('18-05-2022', 'dd-MM-yyyy'), PARSEDATETIME('12-05-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1012, 9, 2, PARSEDATETIME('16-11-2022', 'dd-MM-yyyy'), PARSEDATETIME('15-03-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1013, 2, 2, PARSEDATETIME('06-03-2023', 'dd-MM-yyyy'), PARSEDATETIME('19-10-2024', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1014, 2, 1, PARSEDATETIME('18-07-2022', 'dd-MM-yyyy'), PARSEDATETIME('02-09-2023', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1015, 8, 5, PARSEDATETIME('12-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('23-12-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1016, 2, 5, PARSEDATETIME('04-01-2023', 'dd-MM-yyyy'), PARSEDATETIME('15-08-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1017, 6, 1, PARSEDATETIME('08-09-2022', 'dd-MM-yyyy'), PARSEDATETIME('17-05-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1018, 4, 4, PARSEDATETIME('11-11-2022', 'dd-MM-yyyy'), PARSEDATETIME('12-05-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1019, 3, 5, PARSEDATETIME('13-01-2023', 'dd-MM-yyyy'), PARSEDATETIME('31-12-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1020, 4, 4, PARSEDATETIME('27-02-2023', 'dd-MM-yyyy'), PARSEDATETIME('28-03-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1021, 8, 4, PARSEDATETIME('06-02-2023', 'dd-MM-yyyy'), PARSEDATETIME('11-09-2023', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1022, 3, 4, PARSEDATETIME('07-10-2022', 'dd-MM-yyyy'), PARSEDATETIME('20-06-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1023, 9, 5, PARSEDATETIME('20-05-2022', 'dd-MM-yyyy'), PARSEDATETIME('23-08-2023', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1024, 9, 1, PARSEDATETIME('18-01-2023', 'dd-MM-yyyy'), PARSEDATETIME('26-08-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1025, 2, 3, PARSEDATETIME('24-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('15-08-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1026, 7, 4, PARSEDATETIME('21-05-2022', 'dd-MM-yyyy'), PARSEDATETIME('01-02-2024', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1027, 1, 1, PARSEDATETIME('22-04-2023', 'dd-MM-yyyy'), PARSEDATETIME('27-04-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1028, 2, 2, PARSEDATETIME('22-01-2022', 'dd-MM-yyyy'), PARSEDATETIME('21-11-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1029, 8, 2, PARSEDATETIME('13-01-2022', 'dd-MM-yyyy'), PARSEDATETIME('24-05-2023', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1030, 6, 1, PARSEDATETIME('29-04-2022', 'dd-MM-yyyy'), PARSEDATETIME('04-06-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1031, 9, 5, PARSEDATETIME('26-01-2022', 'dd-MM-yyyy'), PARSEDATETIME('18-01-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1032, 6, 2, PARSEDATETIME('22-05-2022', 'dd-MM-yyyy'), PARSEDATETIME('09-08-2024', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1033, 6, 5, PARSEDATETIME('03-03-2023', 'dd-MM-yyyy'), PARSEDATETIME('21-10-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1034, 6, 1, PARSEDATETIME('31-03-2022', 'dd-MM-yyyy'), PARSEDATETIME('27-07-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1035, 1, 3, PARSEDATETIME('27-01-2022', 'dd-MM-yyyy'), PARSEDATETIME('07-12-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1036, 8, 5, PARSEDATETIME('02-09-2022', 'dd-MM-yyyy'), PARSEDATETIME('22-04-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1037, 9, 3, PARSEDATETIME('28-07-2022', 'dd-MM-yyyy'), PARSEDATETIME('30-01-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1038, 6, 4, PARSEDATETIME('01-03-2023', 'dd-MM-yyyy'), PARSEDATETIME('01-08-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1039, 9, 1, PARSEDATETIME('03-04-2023', 'dd-MM-yyyy'), PARSEDATETIME('12-07-2023', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1040, 4, 1, PARSEDATETIME('27-01-2022', 'dd-MM-yyyy'), PARSEDATETIME('17-03-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1041, 8, 5, PARSEDATETIME('09-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('06-12-2023', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1042, 4, 3, PARSEDATETIME('30-04-2023', 'dd-MM-yyyy'), PARSEDATETIME('25-05-2023', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1043, 2, 3, PARSEDATETIME('23-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('23-05-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1044, 5, 5, PARSEDATETIME('28-07-2022', 'dd-MM-yyyy'), PARSEDATETIME('25-08-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1045, 8, 3, PARSEDATETIME('24-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('31-12-2023', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1046, 9, 1, PARSEDATETIME('05-04-2023', 'dd-MM-yyyy'), PARSEDATETIME('13-05-2023', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1047, 1, 5, PARSEDATETIME('26-03-2022', 'dd-MM-yyyy'), PARSEDATETIME('12-06-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1048, 9, 1, PARSEDATETIME('24-03-2022', 'dd-MM-yyyy'), PARSEDATETIME('11-08-2024', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1049, 3, 1, PARSEDATETIME('02-03-2022', 'dd-MM-yyyy'), PARSEDATETIME('24-10-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1050, 9, 1, PARSEDATETIME('23-09-2022', 'dd-MM-yyyy'), PARSEDATETIME('17-11-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1051, 9, 1, PARSEDATETIME('14-01-2023', 'dd-MM-yyyy'), PARSEDATETIME('19-10-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1052, 3, 4, PARSEDATETIME('20-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('13-11-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1053, 3, 3, PARSEDATETIME('02-09-2022', 'dd-MM-yyyy'), PARSEDATETIME('24-05-2024', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1054, 5, 5, PARSEDATETIME('27-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('14-07-2023', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1055, 5, 4, PARSEDATETIME('20-07-2022', 'dd-MM-yyyy'), PARSEDATETIME('21-02-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1056, 5, 2, PARSEDATETIME('16-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('25-01-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1057, 7, 5, PARSEDATETIME('13-04-2023', 'dd-MM-yyyy'), PARSEDATETIME('16-03-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1058, 8, 2, PARSEDATETIME('08-06-2022', 'dd-MM-yyyy'), PARSEDATETIME('23-08-2024', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1059, 8, 2, PARSEDATETIME('10-04-2023', 'dd-MM-yyyy'), PARSEDATETIME('14-05-2023', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1060, 4, 4, PARSEDATETIME('15-08-2022', 'dd-MM-yyyy'), PARSEDATETIME('12-01-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1061, 9, 3, PARSEDATETIME('25-01-2023', 'dd-MM-yyyy'), PARSEDATETIME('18-11-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1062, 6, 5, PARSEDATETIME('20-03-2022', 'dd-MM-yyyy'), PARSEDATETIME('31-08-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1063, 2, 3, PARSEDATETIME('29-01-2023', 'dd-MM-yyyy'), PARSEDATETIME('19-09-2023', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1064, 6, 2, PARSEDATETIME('28-05-2022', 'dd-MM-yyyy'), PARSEDATETIME('22-12-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1065, 3, 2, PARSEDATETIME('03-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('05-07-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1066, 4, 1, PARSEDATETIME('16-09-2022', 'dd-MM-yyyy'), PARSEDATETIME('24-08-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1067, 8, 3, PARSEDATETIME('01-02-2023', 'dd-MM-yyyy'), PARSEDATETIME('20-10-2023', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1068, 8, 4, PARSEDATETIME('08-03-2023', 'dd-MM-yyyy'), PARSEDATETIME('02-12-2023', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1069, 7, 3, PARSEDATETIME('23-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('28-07-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1070, 2, 4, PARSEDATETIME('14-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('11-12-2023', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1071, 8, 1, PARSEDATETIME('09-08-2022', 'dd-MM-yyyy'), PARSEDATETIME('26-11-2023', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1072, 5, 3, PARSEDATETIME('07-04-2022', 'dd-MM-yyyy'), PARSEDATETIME('24-05-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1073, 8, 4, PARSEDATETIME('08-04-2022', 'dd-MM-yyyy'), PARSEDATETIME('01-01-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1074, 1, 2, PARSEDATETIME('15-04-2022', 'dd-MM-yyyy'), PARSEDATETIME('21-10-2023', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1075, 6, 4, PARSEDATETIME('05-08-2022', 'dd-MM-yyyy'), PARSEDATETIME('03-07-2024', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1076, 5, 5, PARSEDATETIME('06-11-2022', 'dd-MM-yyyy'), PARSEDATETIME('29-11-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1077, 5, 5, PARSEDATETIME('05-07-2022', 'dd-MM-yyyy'), PARSEDATETIME('19-01-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1078, 6, 4, PARSEDATETIME('23-10-2022', 'dd-MM-yyyy'), PARSEDATETIME('28-07-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1079, 6, 1, PARSEDATETIME('28-06-2022', 'dd-MM-yyyy'), PARSEDATETIME('22-12-2023', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1080, 6, 5, PARSEDATETIME('09-08-2022', 'dd-MM-yyyy'), PARSEDATETIME('26-02-2024', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1081, 7, 5, PARSEDATETIME('16-05-2022', 'dd-MM-yyyy'), PARSEDATETIME('13-12-2024', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1082, 3, 5, PARSEDATETIME('12-07-2022', 'dd-MM-yyyy'), PARSEDATETIME('24-06-2023', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1083, 6, 1, PARSEDATETIME('20-06-2022', 'dd-MM-yyyy'), PARSEDATETIME('28-08-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1084, 9, 1, PARSEDATETIME('27-09-2022', 'dd-MM-yyyy'), PARSEDATETIME('16-12-2023', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1085, 8, 5, PARSEDATETIME('04-10-2022', 'dd-MM-yyyy'), PARSEDATETIME('28-08-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1086, 9, 4, PARSEDATETIME('16-04-2023', 'dd-MM-yyyy'), PARSEDATETIME('01-04-2024', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1087, 6, 4, PARSEDATETIME('11-01-2023', 'dd-MM-yyyy'), PARSEDATETIME('26-12-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1088, 5, 3, PARSEDATETIME('20-01-2023', 'dd-MM-yyyy'), PARSEDATETIME('04-10-2023', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1089, 3, 5, PARSEDATETIME('13-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('02-09-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1090, 7, 3, PARSEDATETIME('26-09-2022', 'dd-MM-yyyy'), PARSEDATETIME('18-11-2024', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1091, 9, 5, PARSEDATETIME('25-06-2022', 'dd-MM-yyyy'), PARSEDATETIME('16-11-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1092, 9, 5, PARSEDATETIME('23-03-2023', 'dd-MM-yyyy'), PARSEDATETIME('21-01-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1093, 7, 3, PARSEDATETIME('11-07-2022', 'dd-MM-yyyy'), PARSEDATETIME('27-05-2024', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1094, 6, 3, PARSEDATETIME('28-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('21-10-2023', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1095, 7, 4, PARSEDATETIME('06-10-2022', 'dd-MM-yyyy'), PARSEDATETIME('01-10-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1096, 7, 1, PARSEDATETIME('25-11-2022', 'dd-MM-yyyy'), PARSEDATETIME('01-10-2024', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1097, 2, 5, PARSEDATETIME('17-10-2022', 'dd-MM-yyyy'), PARSEDATETIME('30-10-2024', 'dd-MM-yyyy'), 'Morning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1098, 8, 5, PARSEDATETIME('19-03-2022', 'dd-MM-yyyy'), PARSEDATETIME('09-08-2023', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1099, 5, 1, PARSEDATETIME('26-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('05-06-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1100, 8, 4, PARSEDATETIME('19-02-2022', 'dd-MM-yyyy'), PARSEDATETIME('25-07-2024', 'dd-MM-yyyy'), 'PrimeTime');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1101, 4, 5, PARSEDATETIME('04-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('24-10-2023', 'dd-MM-yyyy'), 'Afternoon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1102, 8, 3, PARSEDATETIME('07-02-2023', 'dd-MM-yyyy'), PARSEDATETIME('23-08-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1103, 8, 1, PARSEDATETIME('05-06-2022', 'dd-MM-yyyy'), PARSEDATETIME('18-05-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1104, 8, 3, PARSEDATETIME('05-05-2022', 'dd-MM-yyyy'), PARSEDATETIME('26-08-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1105, 8, 1, PARSEDATETIME('19-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('05-08-2024', 'dd-MM-yyyy'), 'Noon');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1106, 1, 1, PARSEDATETIME('31-12-2022', 'dd-MM-yyyy'), PARSEDATETIME('29-07-2023', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1107, 8, 1, PARSEDATETIME('05-03-2022', 'dd-MM-yyyy'), PARSEDATETIME('27-05-2024', 'dd-MM-yyyy'), 'EarlyMorning');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1108, 5, 1, PARSEDATETIME('25-04-2022', 'dd-MM-yyyy'), PARSEDATETIME('14-01-2024', 'dd-MM-yyyy'), 'LateNight');
INSERT INTO ads ( id, duration, rep_per_zone, starting_date, ending_date, timezone) VALUES ( 1109, 7, 3, PARSEDATETIME('09-05-2022', 'dd-MM-yyyy'), PARSEDATETIME('01-09-2024', 'dd-MM-yyyy'), 'PrimeTime');

