---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: eebba54d6119b12f7eaab8b1a3a602a5837d849d
    app.quarkus.io/vcs-uri: https://github.com/softeng-aueb/team3-pt-2022-23.git
    app.quarkus.io/build-timestamp: 2024-04-01 - 15:09:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8081"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: content-service
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
  name: content-service
spec:
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30031
  selector:
    app.kubernetes.io/name: content-service
    app.kubernetes.io/version: 1.0.0
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: eebba54d6119b12f7eaab8b1a3a602a5837d849d
    app.quarkus.io/vcs-uri: https://github.com/softeng-aueb/team3-pt-2022-23.git
    app.quarkus.io/build-timestamp: 2024-04-01 - 15:09:42 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8081"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: content-service
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
  name: content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: content-service
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: eebba54d6119b12f7eaab8b1a3a602a5837d849d
        app.quarkus.io/vcs-uri: https://github.com/softeng-aueb/team3-pt-2022-23.git
        app.quarkus.io/build-timestamp: 2024-04-01 - 15:09:42 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8081"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: content-service
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: herculeschrysanthos/content:1.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: content-service
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
