apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: sifavs/user:1.0     # Docker image name and tag
          ports:
            - containerPort: 8080         # Port on which your Quarkus application listens
#          env:
#            - name: ENVIRONMENT_VARIABLE1  # Environment variables used by your application
#              value: value1
#            - name: ENVIRONMENT_VARIABLE2
#              value: value2
