apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.55
          ports:
            - containerPort: 14250
              protocol: UDP
            - containerPort: 14268
            - containerPort: 16686
            - containerPort: 4317
            - containerPort: 4318
            - containerPort: 5775
              protocol: UDP
            - containerPort: 5778
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 9411

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
      nodePort: 30033
    - name: zk-compact-trft
      port: 5775
      targetPort: 5775
      protocol: UDP
    - name: jg-collector-grpc
      port: 14250
      targetPort: 14250
    - name: jg-collector-http
      port: 14268
      targetPort: 14268
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
    - name: config-rest
      port: 5778
      targetPort: 5778
    - name: jg-compact-trft
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: jg-binary-trft
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: zipkin
      port: 9411
      targetPort: 9411
