apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    api: user
    app: user-service
spec:
  containers:
    - name: user
      image: sifavs/user:1.0
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /q/health/ready
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /q/health/live
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3