apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    tier: backend
    app: user
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    api: user
